apiVersion: v1
kind: Secret
metadata:
  name: quay
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ .Values.quay.host }}": {
          "username": "{{ .Values.quay.username }}",
          "password": "{{ .Values.quay.password }}",
          "email": "{{ .Values.quay.email }}",
          "auth": "{{ printf "%s:%s" .Values.quay.username .Values.quay.password | b64enc }}"
        }
      }
    }