apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-token
type: Opaque
stringData:
  SONAR_TOKEN: "squ_a0cae6ac229b660e394e2ce1acc4c8d86ee2ec27"
  SONAR_HOST_URL: "http://sonarqube-sonarqube.sonarqube.svc.cluster.local:9000"