---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: generic-buildah
spec:
  params:
    - name: GIT_REPO
    - name: GIT_BRANCH
    - name: GIT_COMMIT_ID
    - name: GIT_REPO_NAME
    - name: IMAGE_URL
      default: "image-registry.openshift-image-registry.svc.cluster.local:5000"
    - name: MAVEN_IMAGE
      default: "docker.io/library/maven:3.9.6-eclipse-temurin-17"

  workspaces:
    - name: shared-workspace

  tasks:
    - name: git-clone-repo-app
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
      params:
        - name: URL
          value: $(params.GIT_REPO)
        - name: REVISION
          value: $(params.GIT_BRANCH)
      workspaces:
        - name: output
          workspace: shared-workspace
          subPath: source-code

    - name: maven
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: maven
          - name: namespace
            value: {{ .Release.Namespace }}
      params:
        - name: MAVEN_IMAGE
          value: $(params.MAVEN_IMAGE)
      workspaces:
        - name: output
          workspace: shared-workspace
          subPath: source-code

    - name: sonar-scan
      params:
        - name: PROJECT_KEY
          value: $(params.GIT_REPO_NAME)
        - name: PROJECT_NAME
          value: $(params.GIT_REPO_NAME)
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: sonar-scan
          - name: namespace
            value: {{ .Release.Namespace }}
      workspaces:
        - name: source
          workspace: shared-workspace
          subPath: source-code
      runAfter:
        - git-clone-repo-app

    - name: sonar-quality-gate
      params:
        - name: PROJECT_KEY
          value: $(params.GIT_REPO_NAME)

      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: sonar-quality-gate
          - name: namespace
            value: {{ .Release.Namespace }}
      runAfter:
        - sonar-scan

    - name: build-image
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
      params:
        - name: IMAGE
          value: $(params.IMAGE_URL)/$(params.GIT_REPO_NAME):$(params.GIT_BRANCH)-$(params.GIT_COMMIT_ID)
        - name: TLS_VERIFY
          value: 'false'
      workspaces:
        - name: source
          workspace: shared-workspace
          subPath: source-code
      runAfter:
        - sonar-scan