---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: generic-buildah
spec:
  params:
    - name: GIT_REPO
    - name: GIT_BRANCH
    - name: GIT_COMMIT_ID
    - name: GIT_REPO_NAME

  workspaces:
    - name: shared-workspace

  tasks:
    - name: git-clone-repo-app
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
      params:
        - name: URL
          value: $(params.GIT_REPO)
        - name: REVISION
          value: $(params.GIT_BRANCH)
      workspaces:
        - name: output
          workspace: shared-workspace
          subPath: source-code

    - name: build-image
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
      params:
        - name: IMAGE
          value: $(params.GIT_REPO):$(params.GIT_BRANCH)-$(params.GIT_COMMIT_ID)
      workspaces:
        - name: output
          workspace: shared-workspace
          subPath: source-code
      runAfter:
        - git-clone-repo-app