apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: maven
spec:
  params:
    - name: MAVEN_IMAGE
  workspaces:
    - name: source

  steps:
    - name: maven
      image: $(params.MAVEN_IMAGE)
      script: |
        cd $(workspaces.source.path)
        mvn clean package -DskipTests