apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: maven
spec:
  params:
    - name: IMAGE_MAVEN
  workspaces:
    - name: source

  steps:
    - name: maven
      image: $(params.IMAGEM_MAVEN)
      script: |
        mvn clean package -DskipTests