apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: sonar-scan
spec:
  params:
    - name: SONAR_HOST_URL
      default: "http://sonarqube-sonarqube.sonarqube.svc.cluster.local:9000"
    - name: PROJECT_KEY
    - name: PROJECT_NAME
  workspaces:
    - name: source

  steps:
    - name: sonar
      image: sonarsource/sonar-scanner-cli:latest
      workingDir: $(workspaces.source.path)
      env:
        - name: SONAR_TOKEN
          valueFrom:
            secretKeyRef:
              name: sonarqube-token
              key: SONAR_TOKEN
        - name: SONAR_HOST_URL
          valueFrom:
            secretKeyRef:
              name: sonarqube-token
              key: SONAR_HOST_URL

      script: |
        if [ -d ./target/classes ] ; then
          echo "Definindo sonar java binaries"
          SONAR_OPTS="-Dsonar.java.binaries=target/classes"
        fi

        CMD="sonar-scanner \
        -Dsonar.projectKey=$(params.PROJECT_KEY) \
        -Dsonar.projectName=$(params.PROJECT_NAME) \
        -Dsonar.sources=. \
        -Dsonar.host.url=$(params.SONAR_HOST_URL) \
        -Dsonar.token=$SONAR_TOKEN \
        $SONAR_OPTS"

        echo "
        SONAR SERVER: $(params.SONAR_HOST_URL)
        SONAR PROJECT: $(params.PROJECT_NAME)
        COMMAND: $CMD
        PATH: $(pwd)
        "
        eval $CMD