apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: generic-buildah
spec:
  serviceAccountName: pipeline

  triggers:
    - name: generic-buildah
      interceptors:
        - ref:
            name: cel
          params:
            - name: overlays
              value:
                - key: MAVEN_IMAGE
                  expression: "has(body.repository.MAVEN_IMAGE) ? body.repository.MAVEN_IMAGE : ''"
      bindings:
        - ref: generic-buildah

      template:
        ref: generic-buildah