---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: generic-buildah
spec:
  host: 
  to:
    kind: Service
    name: el-generic-buildah
    weight: 100
  port:
    targetPort: http-listener
  wildcardPolicy: None
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
