apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: generic-buildah
spec:
  params:
    - name: GIT_REPO
      value: $(body.repository.ssh_url)

    - name: GIT_BRANCH
      value: $(body.ref)

    - name: GIT_COMMIT_ID
      value: $(body.commits.id)

    - name: GIT_REPO_NAME
      value: $(body.repository.name)